version: 2
jobs:
  build:  
    branches:
      only:
        - master
  
    working_directory: ~/workspace
    
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout # check out source code to working directory
      - run: mvn clean package # run the actual tests
      - store_artifacts: # Upload to: https://circleci.com/docs/2.0/artifacts/
          path: target/org.cuidamane.server-0.0.1-SNAPSHOT.jar
          
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    

