version: 2
jobs:
  build:  
    branches:
      only:
        - master
  
    working_directory: ~/workspace
    
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout # check out source code to working directory
      - run: mvn clean install # run the actual tests
      
      #- store_artifacts: # store the uberjar as an artifact
      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #    path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    

