version: 2
jobs:
  build:  
    branches:
      only:
        - master
  
    working_directory: ~/workspace
    
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout # check out source code to working directory
      - run: mvn clean package
      #- run: mvn -f ~/workspace/org.cuidamane.server/pom.xml package
          
      - store_artifacts:
          path: ~/workspace/org.cuidamane.server/target/org.cuidamane.server-0.0.1-SNAPSHOT.jar
          destination: org.cuidamane.server-0.0.1-SNAPSHOT.jar
          
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    

