swagger: '2.0'
info:
  version: 1.0.0
  title: Agenda Telefonica
paths:

  /phonebook/contacts/id/{id1}/phones:

    'post':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            number:
              type: string
            type:
              type: string
              enum:
              - CELLPHONE
              - HOME
              - OFFICE
              - OTHER

    'get':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

    'put':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            id:
              type: string
            number:
              type: string
            type:
              type: string
              enum:
              - CELLPHONE
              - HOME
              - OFFICE
              - OTHER

    'patch':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            id:
              type: string
            number:
              type: string
            type:
              type: string
              enum:
              - CELLPHONE
              - HOME
              - OFFICE
              - OTHER

    'delete':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            type: boolean
      parameters:
      - in: path
        type: string
        name: id1
        required: true


  /phonebook/contacts/id/{id1}/phones/id/{id2}:

    'get':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

      - in: path
        type: string
        name: id2
        required: true

    'delete':
      tags:
        - Phone
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Phone'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

      - in: path
        type: string
        name: id2
        required: true


  /phonebook/contacts:

    'post':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contact'
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            firstName:
              type: string
            surname:
              type: string

    'get':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
    'put':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contact'
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            id:
              type: string
            phones:
              type: array
            firstName:
              type: string
            surname:
              type: string

    'patch':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contact'
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            id:
              type: string
            phones:
              type: array
            firstName:
              type: string
            surname:
              type: string

    'delete':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            type: boolean

  /phonebook/contacts/id/{id1}:

    'get':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contact'
      parameters:
      - in: path
        type: string
        name: id1
        required: true

    'delete':
      tags:
        - Contact
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Contact'
      parameters:
      - in: path
        type: string
        name: id1
        required: true


definitions:

  Phone:
    type: object
    properties:
      id:
        type: string
      number:
        type: string
      type:
        type: string

  Contact:
    type: object
    properties:
      id:
        type: string
      phones:
        type: array
      firstName:
        type: string
      surname:
        type: string
